Class {
	#name : #GtTreePagerHorizontalTreeFlowNode,
	#superclass : #Object,
	#instVars : [
		'paneModel',
		'row'
	],
	#category : #'GToolkit-Pager-Tree Pager'
}

{ #category : #accessing }
GtTreePagerHorizontalTreeFlowNode >> paneModel [
	^ paneModel
]

{ #category : #accessing }
GtTreePagerHorizontalTreeFlowNode >> paneModel: anObject [
	paneModel := anObject
]

{ #category : #accessing }
GtTreePagerHorizontalTreeFlowNode >> row [
	^ row
]

{ #category : #accessing }
GtTreePagerHorizontalTreeFlowNode >> row: anObject [
	row := anObject
]
