Class {
	#name : #GtTreePagerHorizontalTreeFlowNode,
	#superclass : #Object,
	#instVars : [
		'paneModel',
		'shift'
	],
	#category : #'GToolkit-Pager-Tree Pager'
}

{ #category : #accessing }
GtTreePagerHorizontalTreeFlowNode >> paneModel [
	^ paneModel
]

{ #category : #accessing }
GtTreePagerHorizontalTreeFlowNode >> paneModel: anObject [
	paneModel := anObject
]

{ #category : #accessing }
GtTreePagerHorizontalTreeFlowNode >> shift [
	^ shift
]

{ #category : #accessing }
GtTreePagerHorizontalTreeFlowNode >> shift: anObject [
	shift := anObject
]
