Trait {
	#name : #TGtTreePagerLinkStateVisitor,
	#category : #'GToolkit-Pager-Tree Pager'
}

{ #category : #visiting }
TGtTreePagerLinkStateVisitor >> visitGtTreePagerLinkActiveSelectedState: aState [
	self visitGtTreePagerLinkState: aState
]

{ #category : #visiting }
TGtTreePagerLinkStateVisitor >> visitGtTreePagerLinkActiveSpawnedState: aState [
	self visitGtTreePagerLinkState: aState
]

{ #category : #visiting }
TGtTreePagerLinkStateVisitor >> visitGtTreePagerLinkInactiveCollapsedState: aState [
	self visitGtTreePagerLinkState: aState
]

{ #category : #visiting }
TGtTreePagerLinkStateVisitor >> visitGtTreePagerLinkInactiveHiddenState: aState [
	self visitGtTreePagerLinkState: aState
]

{ #category : #visiting }
TGtTreePagerLinkStateVisitor >> visitGtTreePagerLinkInactiveSpawnedState: aState [
	self visitGtTreePagerLinkState: aState
]

{ #category : #visiting }
TGtTreePagerLinkStateVisitor >> visitGtTreePagerLinkState: aState [
	
]
